a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, fr, es, de]      # [1-a]
    default_locale: en             # [1-b]
    required_locales: [fr]         # [1-c]
    manager_registry: doctrine     # [2]
    templating: "a2lix/default.html.twig"      # [3]
