easy_admin:
    site_name: '<img src="https://test.fads6-admin.fiareads.com/bundles/faadmin/images/fiare-logo-2.png" />'
    design:
        color_scheme: 'dark'
        menu:
          - { label: 'Report Builder' }
          - { entity: 'ReportSchema', label: 'Report Schema', icon: 'fa-cogs' }
          - { entity: 'Page', label: 'Page',      icon: 'fa-gear' }
          - label: 'Culture'
          - { label: 'en', route: 'change_locale', params: { _locale: 'en' } }
          - { label: 'fi', route: 'change_locale', params: { _locale: 'fi' } }
          - { label: '%app.version%' }
          - label: 'About'
            children:
                - { label: 'Help', url: 'http://example.com/external-docs' }
                - { label: 'Docs', url: 'http://example.com/external-docs' }
                - { label: '%app.version%' }
    entities:
        ReportSchema:
            class: App\Entity\ReportSchema
            list:
              fields: ['id', 'name', 'ReportTypeName', 'dimension', {property: 'is_aggregation', 'label': 'Status', type: 'boolean'}, {property: 'is_active', 'label': 'Status', type: 'boolean'}]

            form:
              fields:
                  - {property: 'name', label: 'Name'}
                  - {property: 'report_type', type: 'App\Form\Type\ReportType'}
                  - {property: 'dimension', label: 'Dimensions'}
                  - {property: 'is_aggregation', label: 'Is aggregation required'}
                  - {property: 'is_active', label: 'Status'}
                  - {property: 'imageFile', type: 'vich_image' }
        Page:
             class: App\Entity\Page
             list:
               fields: ['id', 'title', 'content', {property: 'is_active', 'label': 'Status', type: 'boolean'}, {property: 'image', type: 'image', base_path: '%app.path.page_images%'}]
             form:
               fields:
                   - {property: 'title', label: 'Title'}
                   - {property: 'content', label: 'Content'}
                   - {property: 'is_active', label: 'Status'}
                   - {property: 'imageFile', type: 'vich_image' }
