# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:

        app.page.flysystem_adapter:
            awss3v3:
                client: app.amazon_client
                bucket: "%amazon.s3.bucket%"
                prefix: 'uploads/page'

        default_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'


    filesystems:
        page_image_fs:
            adapter: app.page.flysystem_adapter
            mount: page_image_fs

        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
