# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        app.flysystem_adapter:
            awss3v3:
                client: app.amazon_client
                bucket: "%amazon.s3.bucket%"
                prefix: 'gunvant/gapati'
    filesystems:
        page_image_fs:
            adapter: app.flysystem_adapter
            mount: page_image_fs
